const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');const path=require('path');const fs=require('fs');
const app=express();const PORT=process.env.PORT||10000;const OWNER_PASSWORD=process.env.OWNER_PASSWORD||'@ND0710';const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET';const ORIGIN=process.env.FRONTEND_ORIGIN||'*';
app.use(cors({origin:ORIGIN==='*'?'*':ORIGIN,methods:['GET','POST','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));app.use(express.json({limit:'25mb'}));
const DATA_DIR=process.env.DATA_DIR||'/var/data';let dir=DATA_DIR;try{fs.mkdirSync(dir,{recursive:true})}catch(e){dir=path.join(__dirname,'data');fs.mkdirSync(dir,{recursive:true})}if(!fs.existsSync(dir)){dir=path.join(__dirname,'data');fs.mkdirSync(dir,{recursive:true})}
const db=new Database(path.join(dir,'the-web-developer.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,type TEXT NOT NULL,websiteName TEXT NOT NULL,category TEXT DEFAULT '',price TEXT DEFAULT '',soldPrice TEXT DEFAULT '',liveWebsiteLink TEXT DEFAULT '',websiteURL TEXT DEFAULT '',customerName TEXT DEFAULT '',customerMobile TEXT DEFAULT '',projectInformation TEXT DEFAULT '',description TEXT DEFAULT '',paperWork TEXT DEFAULT '',policy TEXT DEFAULT '',signature TEXT DEFAULT '',favorite INTEGER DEFAULT 0,status TEXT DEFAULT '',createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),policy TEXT DEFAULT '',banner TEXT DEFAULT '',updatedAt TEXT NOT NULL);INSERT OR IGNORE INTO settings(id,policy,banner,updatedAt) VALUES(1,'','',datetime('now'));`);
const DEFAULT_POLICY=`PRIVATE CUSTOMER POLICY\n\n1. The customer information provided in this form is private.\n\n2. Website/project information should be used only for the agreed project.\n\n3. The customer confirms that the information provided by them is correct.\n\n4. The customer confirms their agreement by signing below.\n\n5. This document is maintained as project paperwork.`;
const now=()=>new Date().toISOString();const id=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);const out=r=>r?{...r,favorite:Boolean(r.favorite)}:null;
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired token'})}}
function normalize(b,e={}){const p={...e,...b};return{id:String(p.id||id()),type:String(p.type||'demo'),websiteName:String(p.websiteName||'').trim(),category:String(p.category||''),price:String(p.price??''),soldPrice:String(p.soldPrice??''),liveWebsiteLink:String(p.liveWebsiteLink||''),websiteURL:String(p.websiteURL||p.liveWebsiteLink||''),customerName:String(p.customerName||''),customerMobile:String(p.customerMobile||''),projectInformation:String(p.projectInformation||p.description||''),description:String(p.description||p.projectInformation||''),paperWork:String(p.paperWork||''),policy:String(p.policy||''),signature:String(p.signature||''),favorite:p.favorite?1:0,status:String(p.status||(p.type==='real'?'Sold':'Demo')),createdAt:e.createdAt||p.createdAt||now(),updatedAt:now()}}
app.get('/',(q,s)=>s.json({ok:true,service:'THE WEB DEVELOPER API',message:'Backend is running'}));app.get('/api/health',(q,s)=>s.json({ok:true,service:'THE WEB DEVELOPER API'}));
app.post('/api/auth/login',(q,s)=>{const n=String(q.body.name||'').trim().toUpperCase(),p=String(q.body.password||'');if(n!=='DEVENDRA GARG'||p!==OWNER_PASSWORD)return s.status(401).json({error:'Invalid name or password'});s.json({ok:true,token:jwt.sign({role:'owner',name:'DEVENDRA GARG'},JWT_SECRET,{expiresIn:'30d'})})});
app.get('/api/projects',auth,(q,s)=>s.json(db.prepare('SELECT * FROM projects ORDER BY createdAt DESC').all().map(out)));
app.get('/api/projects/:id',auth,(q,s)=>{const r=db.prepare('SELECT * FROM projects WHERE id=?').get(String(q.params.id));if(!r)return s.status(404).json({error:'Project not found'});s.json({project:out(r)})});
app.post('/api/projects',auth,(q,s)=>{const p=normalize(q.body);if(!p.websiteName)return s.status(400).json({error:'Website name is required'});try{db.prepare(`INSERT INTO projects(id,type,websiteName,category,price,soldPrice,liveWebsiteLink,websiteURL,customerName,customerMobile,projectInformation,description,paperWork,policy,signature,favorite,status,createdAt,updatedAt) VALUES(@id,@type,@websiteName,@category,@price,@soldPrice,@liveWebsiteLink,@websiteURL,@customerName,@customerMobile,@projectInformation,@description,@paperWork,@policy,@signature,@favorite,@status,@createdAt,@updatedAt)`).run(p);s.status(201).json({ok:true,project:out(p)})}catch(e){s.status(500).json({error:'Could not save project',details:e.message})}});
app.put('/api/projects/:id',auth,(q,s)=>{const i=String(q.params.id),e=db.prepare('SELECT * FROM projects WHERE id=?').get(i);if(!e)return s.status(404).json({error:'Project not found'});const p=normalize({...q.body,id:i},e);try{db.prepare(`UPDATE projects SET type=@type,websiteName=@websiteName,category=@category,price=@price,soldPrice=@soldPrice,liveWebsiteLink=@liveWebsiteLink,websiteURL=@websiteURL,customerName=@customerName,customerMobile=@customerMobile,projectInformation=@projectInformation,description=@description,paperWork=@paperWork,policy=@policy,signature=@signature,favorite=@favorite,status=@status,updatedAt=@updatedAt WHERE id=@id`).run(p);s.json({ok:true,project:out(p)})}catch(e){s.status(500).json({error:'Could not update project',details:e.message})}});
app.delete('/api/projects/:id',auth,(q,s)=>{const r=db.prepare('DELETE FROM projects WHERE id=?').run(String(q.params.id));if(!r.changes)return s.status(404).json({error:'Project not found'});s.json({ok:true,deleted:String(q.params.id)})});
app.get('/api/settings',auth,(q,s)=>{let r=db.prepare('SELECT * FROM settings WHERE id=1').get();if(!r.policy)r.policy=DEFAULT_POLICY;s.json({settings:r})});
app.put('/api/settings/policy',auth,(q,s)=>{const p=String(q.body.policy||'');db.prepare('UPDATE settings SET policy=?,updatedAt=? WHERE id=1').run(p,now());s.json({ok:true,policy:p})});
app.put('/api/settings/banner',auth,(q,s)=>{const b=String(q.body.banner||'');if(!b)return s.status(400).json({error:'Banner is required'});db.prepare('UPDATE settings SET banner=?,updatedAt=? WHERE id=1').run(b,now());s.json({ok:true,banner:b})});
app.use((e,q,s,n)=>{console.error(e);s.status(500).json({error:'Internal server error'})});app.listen(PORT,'0.0.0.0',()=>console.log('THE WEB DEVELOPER API running on '+PORT));
